### PR TITLE
Any interest in having asset_hash work with Rails 2.3.11?

### PR DESCRIPTION
**Pull request by agibralter**
Here is my set up... https://gist.github.com/991732 Rails 2.3.11 doesn't have a `ActionController::Base.asset_path=` setting... Had to monkey patch Rail's AssetTagHelper... But in any case, the `require 'asset_hash/railtie' if defined?(Rails)` line is making it so that I can't use asset_hash at all with Rails 2.3.11...

### CODE REVIEW

**Comment by donaldpiret** [comment]
Thanks a lot for this! Looking into the best way to integrate all of your work into the gem

**Comment by airblade** [comment]
Does asset_hash work with Rails 2.3.x?

**Comment by agibralter** [comment]
@airblade -- my branch does: https://github.com/agibralter/asset_hash check out the gist in my pull request for instructions on how to use it.

**Comment by airblade** [comment]
@agibralter Thank you!

**Pull request merged**
